import "~/styles/globals.css";
import App from "./app";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <App>
        <body>{children}</body>
      </App>
    </html>
  );
}
